DELETE http://localhost:3001/api/blogs/62d98a0ae456d7f27a08c60e
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2MmQ1NGM3M2MyZDJhMmY5NjEwMzY0ZDQiLCJpYXQiOjE2NTg0MjUzMDUsImV4cCI6MTY1ODQyODkwNX0.NaoJCBrPHS2SlYza4GRvcAaEEtmaBUR-YrJ5mlbeLiA